name:                MaximumCity
version:             0.9.9
github:              "githubuser/Threeeyedgod/MaximumCity"
license:             BSD3
author:              "Venkatesh N"
maintainer:          "xyz@example.com"
copyright:           "2020 Venkatesh N"

description:         Please see the README on GitHub at <https://github.com/ThreeEyedGod/MaximumCity#readme>

default-extensions:
  # Recommended for Polysemy
  - DataKinds
  - FlexibleContexts
  - GADTs
  - XGADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - TemplateHaskell
  - XTemplateHaskell

dependencies:
- base >= 4.12 && <5
- aeson >= 2.0.3.0
- text
- integer-gmp
- telegram-api >= 0.7.3.0
- aws-lambda-haskell-runtime
- naqsha >= 0.3.0.1
- protolude >= 0.3.0
- serverless-haskell >= 0.12.6
- amazonka-core 
- amazonka-ssm 
- amazonka 
- amazonka-s3
- polysemy
- polysemy-plugin
- bytestring >= 0.10.12.1
- http-types >= 0.12.3
- wai >= 3.2.1.2
- lens >= 5.0.1
- binary >= 0.8.8.0
- iproute >= 1.7.12
- containers >= 0.6.4.1
- directory >= 1.3.6.2
- filepath >= 1.4.2.1
- template-haskell >= 2.17.0.0
- http-client >= 0.7.11
- http-client-tls >= 0.3.6.1
- either >= 5.0.1.1
- http-conduit >= 2.3.8
- pdf-toolbox-document
- attoparsec >= 0.14.4
- time >= 1.9.3
- word8 >=0.1
- utf8-string
- servant
- servant-server
- mtl >= 2.2.2
- string-interpolate >= 0.3.1.1

library:
  source-dirs: src
  ghc-options: -O2 -flate-specialise -fspecialise-aggressively -fplugin=Polysemy.Plugin

executables:
  bootstrap:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -static
    - -with-rtsopts=-N
    - -XUndecidableSuperClasses
    - -XScopedTypeVariables
    - -flate-specialise 
    - -fspecialise-aggressively
    - -fplugin=Polysemy.Plugin
    cc-options: -static
    ld-options: -static -pthread
    dependencies:
    - MaximumCity

tests:
  MaximumCity-test:
    source-dirs:         test
    main:                TestsMain.hs
    dependencies:        
                       - base 
                       - MaximumCity
                       - test-framework
                       - test-framework-quickcheck2
                       - QuickCheck > 2.14.2
                       - hspec ^>= 2.7.4
#                       - hspec-hedgehog
#                       - hedgehog  >= 1.0.2 && < 2 
                       - hspec-core >= 2.7.4
                       - random-strings >= 0.1.1.0
                       - QuickCheck >= 2.13.2
                       - either >= 5.0.1.1
                       - hspec-expectations >= 0.8.2
                       - process >= 1.6.9.0
                       - polysemy
                       - polysemy-plugin
                       - amazonka-s3 >= 1.6.1
                       - template-haskell
    ghc-options:       -threaded -rtsopts "-with-rtsopts=-N1 -s" -flate-specialise -fspecialise-aggressively -fplugin=Polysemy.Plugin

benchmarks:
  MaximumCity-benchmark:
      main:             Main.hs

default-extensions:
  - RecordWildCards
  - OverloadedLists
  - OverloadedStrings
  - DeriveGeneric
  - UndecidableSuperClasses
  - ScopedTypeVariables