/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package MaximumCity-0.9.9 */
#ifndef VERSION_MaximumCity
#define VERSION_MaximumCity "0.9.9"
#endif /* VERSION_MaximumCity */
#ifndef MIN_VERSION_MaximumCity
#define MIN_VERSION_MaximumCity(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 9)
#endif /* MIN_VERSION_MaximumCity */
/* package aeson-2.0.3.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "2.0.3.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 3)
#endif /* MIN_VERSION_aeson */
/* package amazonka-2.0 */
#ifndef VERSION_amazonka
#define VERSION_amazonka "2.0"
#endif /* VERSION_amazonka */
#ifndef MIN_VERSION_amazonka
#define MIN_VERSION_amazonka(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_amazonka */
/* package amazonka-core-2.0 */
#ifndef VERSION_amazonka_core
#define VERSION_amazonka_core "2.0"
#endif /* VERSION_amazonka_core */
#ifndef MIN_VERSION_amazonka_core
#define MIN_VERSION_amazonka_core(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_amazonka_core */
/* package amazonka-s3-2.0 */
#ifndef VERSION_amazonka_s3
#define VERSION_amazonka_s3 "2.0"
#endif /* VERSION_amazonka_s3 */
#ifndef MIN_VERSION_amazonka_s3
#define MIN_VERSION_amazonka_s3(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_amazonka_s3 */
/* package amazonka-ssm-2.0 */
#ifndef VERSION_amazonka_ssm
#define VERSION_amazonka_ssm "2.0"
#endif /* VERSION_amazonka_ssm */
#ifndef MIN_VERSION_amazonka_ssm
#define MIN_VERSION_amazonka_ssm(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_amazonka_ssm */
/* package attoparsec-0.14.4 */
#ifndef VERSION_attoparsec
#define VERSION_attoparsec "0.14.4"
#endif /* VERSION_attoparsec */
#ifndef MIN_VERSION_attoparsec
#define MIN_VERSION_attoparsec(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  14 || \
  (major1) == 0 && (major2) == 14 && (minor) <= 4)
#endif /* MIN_VERSION_attoparsec */
/* package aws-lambda-haskell-runtime-4.1.1 */
#ifndef VERSION_aws_lambda_haskell_runtime
#define VERSION_aws_lambda_haskell_runtime "4.1.1"
#endif /* VERSION_aws_lambda_haskell_runtime */
#ifndef MIN_VERSION_aws_lambda_haskell_runtime
#define MIN_VERSION_aws_lambda_haskell_runtime(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  1 || \
  (major1) == 4 && (major2) == 1 && (minor) <= 1)
#endif /* MIN_VERSION_aws_lambda_haskell_runtime */
/* package binary-0.8.8.0 */
#ifndef VERSION_binary
#define VERSION_binary "0.8.8.0"
#endif /* VERSION_binary */
#ifndef MIN_VERSION_binary
#define MIN_VERSION_binary(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 8)
#endif /* MIN_VERSION_binary */
/* package bytestring-0.10.12.1 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.12.1"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 12)
#endif /* MIN_VERSION_bytestring */
/* package containers-0.6.4.1 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.4.1"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 4)
#endif /* MIN_VERSION_containers */
/* package directory-1.3.6.2 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.6.2"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 6)
#endif /* MIN_VERSION_directory */
/* package either-5.0.2 */
#ifndef VERSION_either
#define VERSION_either "5.0.2"
#endif /* VERSION_either */
#ifndef MIN_VERSION_either
#define MIN_VERSION_either(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_either */
/* package filepath-1.4.2.1 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.4.2.1"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_filepath */
/* package ghc-9.0.2 */
#ifndef VERSION_ghc
#define VERSION_ghc "9.0.2"
#endif /* VERSION_ghc */
#ifndef MIN_VERSION_ghc
#define MIN_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  0 || \
  (major1) == 9 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_ghc */
/* package http-client-0.7.13.1 */
#ifndef VERSION_http_client
#define VERSION_http_client "0.7.13.1"
#endif /* VERSION_http_client */
#ifndef MIN_VERSION_http_client
#define MIN_VERSION_http_client(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 13)
#endif /* MIN_VERSION_http_client */
/* package http-client-tls-0.3.6.1 */
#ifndef VERSION_http_client_tls
#define VERSION_http_client_tls "0.3.6.1"
#endif /* VERSION_http_client_tls */
#ifndef MIN_VERSION_http_client_tls
#define MIN_VERSION_http_client_tls(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 6)
#endif /* MIN_VERSION_http_client_tls */
/* package http-conduit-2.3.8 */
#ifndef VERSION_http_conduit
#define VERSION_http_conduit "2.3.8"
#endif /* VERSION_http_conduit */
#ifndef MIN_VERSION_http_conduit
#define MIN_VERSION_http_conduit(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 8)
#endif /* MIN_VERSION_http_conduit */
/* package http-types-0.12.3 */
#ifndef VERSION_http_types
#define VERSION_http_types "0.12.3"
#endif /* VERSION_http_types */
#ifndef MIN_VERSION_http_types
#define MIN_VERSION_http_types(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 3)
#endif /* MIN_VERSION_http_types */
/* package integer-gmp-1.1 */
#ifndef VERSION_integer_gmp
#define VERSION_integer_gmp "1.1"
#endif /* VERSION_integer_gmp */
#ifndef MIN_VERSION_integer_gmp
#define MIN_VERSION_integer_gmp(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_integer_gmp */
/* package iproute-1.7.12 */
#ifndef VERSION_iproute
#define VERSION_iproute "1.7.12"
#endif /* VERSION_iproute */
#ifndef MIN_VERSION_iproute
#define MIN_VERSION_iproute(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  7 || \
  (major1) == 1 && (major2) == 7 && (minor) <= 12)
#endif /* MIN_VERSION_iproute */
/* package lens-5.0.1 */
#ifndef VERSION_lens
#define VERSION_lens "5.0.1"
#endif /* VERSION_lens */
#ifndef MIN_VERSION_lens
#define MIN_VERSION_lens(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 1)
#endif /* MIN_VERSION_lens */
/* package liquid-base-4.14.3.0 */
#ifndef VERSION_liquid_base
#define VERSION_liquid_base "4.14.3.0"
#endif /* VERSION_liquid_base */
#ifndef MIN_VERSION_liquid_base
#define MIN_VERSION_liquid_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  14 || \
  (major1) == 4 && (major2) == 14 && (minor) <= 3)
#endif /* MIN_VERSION_liquid_base */
/* package liquid-ghc-prim-0.6.1 */
#ifndef VERSION_liquid_ghc_prim
#define VERSION_liquid_ghc_prim "0.6.1"
#endif /* VERSION_liquid_ghc_prim */
#ifndef MIN_VERSION_liquid_ghc_prim
#define MIN_VERSION_liquid_ghc_prim(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 1)
#endif /* MIN_VERSION_liquid_ghc_prim */
/* package liquidhaskell-0.8.10.7.1 */
#ifndef VERSION_liquidhaskell
#define VERSION_liquidhaskell "0.8.10.7.1"
#endif /* VERSION_liquidhaskell */
#ifndef MIN_VERSION_liquidhaskell
#define MIN_VERSION_liquidhaskell(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 10)
#endif /* MIN_VERSION_liquidhaskell */
/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */
/* package naqsha-0.3.0.1 */
#ifndef VERSION_naqsha
#define VERSION_naqsha "0.3.0.1"
#endif /* VERSION_naqsha */
#ifndef MIN_VERSION_naqsha
#define MIN_VERSION_naqsha(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_naqsha */
/* package pdf-toolbox-document-0.1.2 */
#ifndef VERSION_pdf_toolbox_document
#define VERSION_pdf_toolbox_document "0.1.2"
#endif /* VERSION_pdf_toolbox_document */
#ifndef MIN_VERSION_pdf_toolbox_document
#define MIN_VERSION_pdf_toolbox_document(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 2)
#endif /* MIN_VERSION_pdf_toolbox_document */
/* package polysemy-1.6.0.0 */
#ifndef VERSION_polysemy
#define VERSION_polysemy "1.6.0.0"
#endif /* VERSION_polysemy */
#ifndef MIN_VERSION_polysemy
#define MIN_VERSION_polysemy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 0)
#endif /* MIN_VERSION_polysemy */
/* package polysemy-plugin-0.4.1.1 */
#ifndef VERSION_polysemy_plugin
#define VERSION_polysemy_plugin "0.4.1.1"
#endif /* VERSION_polysemy_plugin */
#ifndef MIN_VERSION_polysemy_plugin
#define MIN_VERSION_polysemy_plugin(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 1)
#endif /* MIN_VERSION_polysemy_plugin */
/* package protolude-0.3.1 */
#ifndef VERSION_protolude
#define VERSION_protolude "0.3.1"
#endif /* VERSION_protolude */
#ifndef MIN_VERSION_protolude
#define MIN_VERSION_protolude(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_protolude */
/* package servant-0.19.1 */
#ifndef VERSION_servant
#define VERSION_servant "0.19.1"
#endif /* VERSION_servant */
#ifndef MIN_VERSION_servant
#define MIN_VERSION_servant(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  19 || \
  (major1) == 0 && (major2) == 19 && (minor) <= 1)
#endif /* MIN_VERSION_servant */
/* package servant-server-0.19.2 */
#ifndef VERSION_servant_server
#define VERSION_servant_server "0.19.2"
#endif /* VERSION_servant_server */
#ifndef MIN_VERSION_servant_server
#define MIN_VERSION_servant_server(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  19 || \
  (major1) == 0 && (major2) == 19 && (minor) <= 2)
#endif /* MIN_VERSION_servant_server */
/* package serverless-haskell-0.12.6 */
#ifndef VERSION_serverless_haskell
#define VERSION_serverless_haskell "0.12.6"
#endif /* VERSION_serverless_haskell */
#ifndef MIN_VERSION_serverless_haskell
#define MIN_VERSION_serverless_haskell(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 6)
#endif /* MIN_VERSION_serverless_haskell */
/* package sort-1.0.0.0 */
#ifndef VERSION_sort
#define VERSION_sort "1.0.0.0"
#endif /* VERSION_sort */
#ifndef MIN_VERSION_sort
#define MIN_VERSION_sort(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_sort */
/* package string-interpolate-0.3.1.2 */
#ifndef VERSION_string_interpolate
#define VERSION_string_interpolate "0.3.1.2"
#endif /* VERSION_string_interpolate */
#ifndef MIN_VERSION_string_interpolate
#define MIN_VERSION_string_interpolate(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_string_interpolate */
/* package stringsearch-0.3.6.6 */
#ifndef VERSION_stringsearch
#define VERSION_stringsearch "0.3.6.6"
#endif /* VERSION_stringsearch */
#ifndef MIN_VERSION_stringsearch
#define MIN_VERSION_stringsearch(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 6)
#endif /* MIN_VERSION_stringsearch */
/* package telegram-api-0.7.3.0 */
#ifndef VERSION_telegram_api
#define VERSION_telegram_api "0.7.3.0"
#endif /* VERSION_telegram_api */
#ifndef MIN_VERSION_telegram_api
#define MIN_VERSION_telegram_api(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 3)
#endif /* MIN_VERSION_telegram_api */
/* package template-haskell-2.17.0.0 */
#ifndef VERSION_template_haskell
#define VERSION_template_haskell "2.17.0.0"
#endif /* VERSION_template_haskell */
#ifndef MIN_VERSION_template_haskell
#define MIN_VERSION_template_haskell(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  17 || \
  (major1) == 2 && (major2) == 17 && (minor) <= 0)
#endif /* MIN_VERSION_template_haskell */
/* package text-1.2.5.0 */
#ifndef VERSION_text
#define VERSION_text "1.2.5.0"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_VERSION_text */
/* package text-manipulate-0.3.1.0 */
#ifndef VERSION_text_manipulate
#define VERSION_text_manipulate "0.3.1.0"
#endif /* VERSION_text_manipulate */
#ifndef MIN_VERSION_text_manipulate
#define MIN_VERSION_text_manipulate(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_text_manipulate */
/* package time-1.9.3 */
#ifndef VERSION_time
#define VERSION_time "1.9.3"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 3)
#endif /* MIN_VERSION_time */
/* package type-natural-1.1.0.1 */
#ifndef VERSION_type_natural
#define VERSION_type_natural "1.1.0.1"
#endif /* VERSION_type_natural */
#ifndef MIN_VERSION_type_natural
#define MIN_VERSION_type_natural(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_type_natural */
/* package utf8-string-1.0.2 */
#ifndef VERSION_utf8_string
#define VERSION_utf8_string "1.0.2"
#endif /* VERSION_utf8_string */
#ifndef MIN_VERSION_utf8_string
#define MIN_VERSION_utf8_string(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_utf8_string */
/* package wai-3.2.3 */
#ifndef VERSION_wai
#define VERSION_wai "3.2.3"
#endif /* VERSION_wai */
#ifndef MIN_VERSION_wai
#define MIN_VERSION_wai(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_wai */
/* package word8-0.1.3 */
#ifndef VERSION_word8
#define VERSION_word8 "0.1.3"
#endif /* VERSION_word8 */
#ifndef MIN_VERSION_word8
#define MIN_VERSION_word8(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 3)
#endif /* MIN_VERSION_word8 */

/* tool gcc-14.0.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "14.0.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  14 || \
  (major1) == 14 && (major2) <  0 || \
  (major1) == 14 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.0.2 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.0.2"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  0 || \
  (major1) == 9 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.0.2 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.0.2"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  0 || \
  (major1) == 9 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.25.1 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.25.1"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  25 || \
  (major1) == 2 && (major2) == 25 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool happy-1.20.0 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "1.20.0"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  20 || \
  (major1) == 1 && (major2) == 20 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_happy */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool hscolour-1.24 */
#ifndef TOOL_VERSION_hscolour
#define TOOL_VERSION_hscolour "1.24"
#endif /* TOOL_VERSION_hscolour */
#ifndef MIN_TOOL_VERSION_hscolour
#define MIN_TOOL_VERSION_hscolour(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  24 || \
  (major1) == 1 && (major2) == 24 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hscolour */
/* tool runghc-9.0.2 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.0.2"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  0 || \
  (major1) == 9 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "MaximumCity-0.9.9-ArprVEGbEGeJFqYM4LtgOt"
#endif /* CURRENT_packageKey */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "MaximumCity-0.9.9-ArprVEGbEGeJFqYM4LtgOt"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.9.9"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package MaximumCity-0.9.9 */
#ifndef VERSION_MaximumCity
#define VERSION_MaximumCity "0.9.9"
#endif /* VERSION_MaximumCity */
#ifndef MIN_VERSION_MaximumCity
#define MIN_VERSION_MaximumCity(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 9)
#endif /* MIN_VERSION_MaximumCity */
/* package MaximumCity-0.9.9 */
#ifndef VERSION_MaximumCity
#define VERSION_MaximumCity "0.9.9"
#endif /* VERSION_MaximumCity */
#ifndef MIN_VERSION_MaximumCity
#define MIN_VERSION_MaximumCity(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 9)
#endif /* MIN_VERSION_MaximumCity */
/* package aeson-2.0.3.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "2.0.3.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 3)
#endif /* MIN_VERSION_aeson */
/* package amazonka-2.0 */
#ifndef VERSION_amazonka
#define VERSION_amazonka "2.0"
#endif /* VERSION_amazonka */
#ifndef MIN_VERSION_amazonka
#define MIN_VERSION_amazonka(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_amazonka */
/* package amazonka-core-2.0 */
#ifndef VERSION_amazonka_core
#define VERSION_amazonka_core "2.0"
#endif /* VERSION_amazonka_core */
#ifndef MIN_VERSION_amazonka_core
#define MIN_VERSION_amazonka_core(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_amazonka_core */
/* package amazonka-s3-2.0 */
#ifndef VERSION_amazonka_s3
#define VERSION_amazonka_s3 "2.0"
#endif /* VERSION_amazonka_s3 */
#ifndef MIN_VERSION_amazonka_s3
#define MIN_VERSION_amazonka_s3(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_amazonka_s3 */
/* package amazonka-ssm-2.0 */
#ifndef VERSION_amazonka_ssm
#define VERSION_amazonka_ssm "2.0"
#endif /* VERSION_amazonka_ssm */
#ifndef MIN_VERSION_amazonka_ssm
#define MIN_VERSION_amazonka_ssm(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_amazonka_ssm */
/* package attoparsec-0.14.4 */
#ifndef VERSION_attoparsec
#define VERSION_attoparsec "0.14.4"
#endif /* VERSION_attoparsec */
#ifndef MIN_VERSION_attoparsec
#define MIN_VERSION_attoparsec(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  14 || \
  (major1) == 0 && (major2) == 14 && (minor) <= 4)
#endif /* MIN_VERSION_attoparsec */
/* package aws-lambda-haskell-runtime-4.1.1 */
#ifndef VERSION_aws_lambda_haskell_runtime
#define VERSION_aws_lambda_haskell_runtime "4.1.1"
#endif /* VERSION_aws_lambda_haskell_runtime */
#ifndef MIN_VERSION_aws_lambda_haskell_runtime
#define MIN_VERSION_aws_lambda_haskell_runtime(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  1 || \
  (major1) == 4 && (major2) == 1 && (minor) <= 1)
#endif /* MIN_VERSION_aws_lambda_haskell_runtime */
/* package binary-0.8.8.0 */
#ifndef VERSION_binary
#define VERSION_binary "0.8.8.0"
#endif /* VERSION_binary */
#ifndef MIN_VERSION_binary
#define MIN_VERSION_binary(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 8)
#endif /* MIN_VERSION_binary */
/* package bytestring-0.10.12.1 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.12.1"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 12)
#endif /* MIN_VERSION_bytestring */
/* package containers-0.6.4.1 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.4.1"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 4)
#endif /* MIN_VERSION_containers */
/* package directory-1.3.6.2 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.6.2"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 6)
#endif /* MIN_VERSION_directory */
/* package either-5.0.2 */
#ifndef VERSION_either
#define VERSION_either "5.0.2"
#endif /* VERSION_either */
#ifndef MIN_VERSION_either
#define MIN_VERSION_either(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_either */
/* package filepath-1.4.2.1 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.4.2.1"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_filepath */
/* package ghc-9.0.2 */
#ifndef VERSION_ghc
#define VERSION_ghc "9.0.2"
#endif /* VERSION_ghc */
#ifndef MIN_VERSION_ghc
#define MIN_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  0 || \
  (major1) == 9 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_ghc */
/* package http-client-0.7.13.1 */
#ifndef VERSION_http_client
#define VERSION_http_client "0.7.13.1"
#endif /* VERSION_http_client */
#ifndef MIN_VERSION_http_client
#define MIN_VERSION_http_client(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 13)
#endif /* MIN_VERSION_http_client */
/* package http-client-tls-0.3.6.1 */
#ifndef VERSION_http_client_tls
#define VERSION_http_client_tls "0.3.6.1"
#endif /* VERSION_http_client_tls */
#ifndef MIN_VERSION_http_client_tls
#define MIN_VERSION_http_client_tls(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 6)
#endif /* MIN_VERSION_http_client_tls */
/* package http-conduit-2.3.8 */
#ifndef VERSION_http_conduit
#define VERSION_http_conduit "2.3.8"
#endif /* VERSION_http_conduit */
#ifndef MIN_VERSION_http_conduit
#define MIN_VERSION_http_conduit(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 8)
#endif /* MIN_VERSION_http_conduit */
/* package http-types-0.12.3 */
#ifndef VERSION_http_types
#define VERSION_http_types "0.12.3"
#endif /* VERSION_http_types */
#ifndef MIN_VERSION_http_types
#define MIN_VERSION_http_types(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 3)
#endif /* MIN_VERSION_http_types */
/* package integer-gmp-1.1 */
#ifndef VERSION_integer_gmp
#define VERSION_integer_gmp "1.1"
#endif /* VERSION_integer_gmp */
#ifndef MIN_VERSION_integer_gmp
#define MIN_VERSION_integer_gmp(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_integer_gmp */
/* package iproute-1.7.12 */
#ifndef VERSION_iproute
#define VERSION_iproute "1.7.12"
#endif /* VERSION_iproute */
#ifndef MIN_VERSION_iproute
#define MIN_VERSION_iproute(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  7 || \
  (major1) == 1 && (major2) == 7 && (minor) <= 12)
#endif /* MIN_VERSION_iproute */
/* package lens-5.0.1 */
#ifndef VERSION_lens
#define VERSION_lens "5.0.1"
#endif /* VERSION_lens */
#ifndef MIN_VERSION_lens
#define MIN_VERSION_lens(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 1)
#endif /* MIN_VERSION_lens */
/* package liquid-base-4.14.3.0 */
#ifndef VERSION_liquid_base
#define VERSION_liquid_base "4.14.3.0"
#endif /* VERSION_liquid_base */
#ifndef MIN_VERSION_liquid_base
#define MIN_VERSION_liquid_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  14 || \
  (major1) == 4 && (major2) == 14 && (minor) <= 3)
#endif /* MIN_VERSION_liquid_base */
/* package liquid-ghc-prim-0.6.1 */
#ifndef VERSION_liquid_ghc_prim
#define VERSION_liquid_ghc_prim "0.6.1"
#endif /* VERSION_liquid_ghc_prim */
#ifndef MIN_VERSION_liquid_ghc_prim
#define MIN_VERSION_liquid_ghc_prim(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 1)
#endif /* MIN_VERSION_liquid_ghc_prim */
/* package liquidhaskell-0.8.10.7.1 */
#ifndef VERSION_liquidhaskell
#define VERSION_liquidhaskell "0.8.10.7.1"
#endif /* VERSION_liquidhaskell */
#ifndef MIN_VERSION_liquidhaskell
#define MIN_VERSION_liquidhaskell(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 10)
#endif /* MIN_VERSION_liquidhaskell */
/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */
/* package naqsha-0.3.0.1 */
#ifndef VERSION_naqsha
#define VERSION_naqsha "0.3.0.1"
#endif /* VERSION_naqsha */
#ifndef MIN_VERSION_naqsha
#define MIN_VERSION_naqsha(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_naqsha */
/* package pdf-toolbox-document-0.1.2 */
#ifndef VERSION_pdf_toolbox_document
#define VERSION_pdf_toolbox_document "0.1.2"
#endif /* VERSION_pdf_toolbox_document */
#ifndef MIN_VERSION_pdf_toolbox_document
#define MIN_VERSION_pdf_toolbox_document(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 2)
#endif /* MIN_VERSION_pdf_toolbox_document */
/* package polysemy-1.6.0.0 */
#ifndef VERSION_polysemy
#define VERSION_polysemy "1.6.0.0"
#endif /* VERSION_polysemy */
#ifndef MIN_VERSION_polysemy
#define MIN_VERSION_polysemy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 0)
#endif /* MIN_VERSION_polysemy */
/* package polysemy-plugin-0.4.1.1 */
#ifndef VERSION_polysemy_plugin
#define VERSION_polysemy_plugin "0.4.1.1"
#endif /* VERSION_polysemy_plugin */
#ifndef MIN_VERSION_polysemy_plugin
#define MIN_VERSION_polysemy_plugin(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 1)
#endif /* MIN_VERSION_polysemy_plugin */
/* package protolude-0.3.1 */
#ifndef VERSION_protolude
#define VERSION_protolude "0.3.1"
#endif /* VERSION_protolude */
#ifndef MIN_VERSION_protolude
#define MIN_VERSION_protolude(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_protolude */
/* package servant-0.19.1 */
#ifndef VERSION_servant
#define VERSION_servant "0.19.1"
#endif /* VERSION_servant */
#ifndef MIN_VERSION_servant
#define MIN_VERSION_servant(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  19 || \
  (major1) == 0 && (major2) == 19 && (minor) <= 1)
#endif /* MIN_VERSION_servant */
/* package servant-server-0.19.2 */
#ifndef VERSION_servant_server
#define VERSION_servant_server "0.19.2"
#endif /* VERSION_servant_server */
#ifndef MIN_VERSION_servant_server
#define MIN_VERSION_servant_server(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  19 || \
  (major1) == 0 && (major2) == 19 && (minor) <= 2)
#endif /* MIN_VERSION_servant_server */
/* package serverless-haskell-0.12.6 */
#ifndef VERSION_serverless_haskell
#define VERSION_serverless_haskell "0.12.6"
#endif /* VERSION_serverless_haskell */
#ifndef MIN_VERSION_serverless_haskell
#define MIN_VERSION_serverless_haskell(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 6)
#endif /* MIN_VERSION_serverless_haskell */
/* package sort-1.0.0.0 */
#ifndef VERSION_sort
#define VERSION_sort "1.0.0.0"
#endif /* VERSION_sort */
#ifndef MIN_VERSION_sort
#define MIN_VERSION_sort(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_sort */
/* package string-interpolate-0.3.1.2 */
#ifndef VERSION_string_interpolate
#define VERSION_string_interpolate "0.3.1.2"
#endif /* VERSION_string_interpolate */
#ifndef MIN_VERSION_string_interpolate
#define MIN_VERSION_string_interpolate(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_string_interpolate */
/* package stringsearch-0.3.6.6 */
#ifndef VERSION_stringsearch
#define VERSION_stringsearch "0.3.6.6"
#endif /* VERSION_stringsearch */
#ifndef MIN_VERSION_stringsearch
#define MIN_VERSION_stringsearch(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 6)
#endif /* MIN_VERSION_stringsearch */
/* package telegram-api-0.7.3.0 */
#ifndef VERSION_telegram_api
#define VERSION_telegram_api "0.7.3.0"
#endif /* VERSION_telegram_api */
#ifndef MIN_VERSION_telegram_api
#define MIN_VERSION_telegram_api(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 3)
#endif /* MIN_VERSION_telegram_api */
/* package template-haskell-2.17.0.0 */
#ifndef VERSION_template_haskell
#define VERSION_template_haskell "2.17.0.0"
#endif /* VERSION_template_haskell */
#ifndef MIN_VERSION_template_haskell
#define MIN_VERSION_template_haskell(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  17 || \
  (major1) == 2 && (major2) == 17 && (minor) <= 0)
#endif /* MIN_VERSION_template_haskell */
/* package text-1.2.5.0 */
#ifndef VERSION_text
#define VERSION_text "1.2.5.0"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_VERSION_text */
/* package text-manipulate-0.3.1.0 */
#ifndef VERSION_text_manipulate
#define VERSION_text_manipulate "0.3.1.0"
#endif /* VERSION_text_manipulate */
#ifndef MIN_VERSION_text_manipulate
#define MIN_VERSION_text_manipulate(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_text_manipulate */
/* package time-1.9.3 */
#ifndef VERSION_time
#define VERSION_time "1.9.3"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 3)
#endif /* MIN_VERSION_time */
/* package type-natural-1.1.0.1 */
#ifndef VERSION_type_natural
#define VERSION_type_natural "1.1.0.1"
#endif /* VERSION_type_natural */
#ifndef MIN_VERSION_type_natural
#define MIN_VERSION_type_natural(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_type_natural */
/* package utf8-string-1.0.2 */
#ifndef VERSION_utf8_string
#define VERSION_utf8_string "1.0.2"
#endif /* VERSION_utf8_string */
#ifndef MIN_VERSION_utf8_string
#define MIN_VERSION_utf8_string(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_utf8_string */
/* package wai-3.2.3 */
#ifndef VERSION_wai
#define VERSION_wai "3.2.3"
#endif /* VERSION_wai */
#ifndef MIN_VERSION_wai
#define MIN_VERSION_wai(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_wai */
/* package word8-0.1.3 */
#ifndef VERSION_word8
#define VERSION_word8 "0.1.3"
#endif /* VERSION_word8 */
#ifndef MIN_VERSION_word8
#define MIN_VERSION_word8(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 3)
#endif /* MIN_VERSION_word8 */

/* tool gcc-14.0.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "14.0.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  14 || \
  (major1) == 14 && (major2) <  0 || \
  (major1) == 14 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.0.2 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.0.2"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  0 || \
  (major1) == 9 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.0.2 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.0.2"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  0 || \
  (major1) == 9 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.25.1 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.25.1"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  25 || \
  (major1) == 2 && (major2) == 25 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool happy-1.20.0 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "1.20.0"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  20 || \
  (major1) == 1 && (major2) == 20 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_happy */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool hscolour-1.24 */
#ifndef TOOL_VERSION_hscolour
#define TOOL_VERSION_hscolour "1.24"
#endif /* TOOL_VERSION_hscolour */
#ifndef MIN_TOOL_VERSION_hscolour
#define MIN_TOOL_VERSION_hscolour(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  24 || \
  (major1) == 1 && (major2) == 24 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hscolour */
/* tool runghc-9.0.2 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.0.2"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  0 || \
  (major1) == 9 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "MaximumCity-0.9.9-93PKqcUn4HgD7jS4ggJWFT-bootstrap"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.9.9"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
